version: '3'

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/html
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3307:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT}
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html
    restart: always

  redis:
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    container_name: redis
    depends_on:
      - wordpress
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  static:
    build:
      context: .
      dockerfile: requirements/bonus/static/Dockerfile
    container_name: static
    ports:
      - "8880:80"
    networks:
      - inception
    restart: always

#  vsftpd:
#    build:
#      context: .
#      dockerfile: requirements/bonus/vsftpd/Dockerfile
#      args:
#        FTP_USR: ${FTP_USR}
#        FTP_PWD: ${FTP_PWD}
#    container_name: vsftpd
#    depends_on:
#      - wordpress
#    ports:
#      - "21:21"
#    volumes:
#      - wp-volume:/var/www/
#    networks:
#     - inception
#    restart: always

  adminer:
    build:
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
     - inception
    restart: always

  cadvisor:
    build:
      context: .
      dockerfile: requirements/bonus/cadvisor/Dockerfile
    container_name: cadvisor
    ports:
       - "6060:8080"
    volumes:
       - /:/rootfs:ro
       - /var/run:/var/run:ro
       - /sys:/sys:ro
       - /var/lib/docker/:/var/lib/docker:ro
    networks:
       - inception
    restart: always

networks:
    inception:
        driver: bridge
